name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches:
    - main
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Compile LaTeX files
      uses: xu-cheng/latex-action@v2
      with:
        root_file: docs/**/*.tex  # Compiles all .tex files

    - name: upload pdfs
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: docs/**/*.pdf


      
