name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
 build_latex:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch enough history to compare with the previous commit
    - name: install git
      run: |
        apt-get update && apt-get install -y git
    - name: build updated pdfs
      run: |
        # Find all changed .tex files in the docs folder
        changed_tex_files=$(git diff --name-only HEAD~1 HEAD -- 'docs/**/*.tex')

        # Compile only the changed .tex files
        for file in $changed_tex_files; do
          echo "Compiling $file..."
          (cd "$(dirname "$file")" && latexmk "$(basename "$file")")
        done
    - name: upload pdfs
      uses: actions/upload-artifact@v3
      with:
        name: updated-pdfs
        path: ./docs/**/*.pdf

      
