name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y texlive-full

    - name: Compile all LaTeX files
      run: |
        # Find all .tex files in the docs directory
        find ./docs -name "*.tex" | while read file; do
          echo "Compiling $file"
          latexmk -pdf -cd "$file"
        done

    - name: upload pdfs
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: docs/**/*.pdf



      
