name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: build pdfs
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
          ./docs/*/*.tex
          ./docs/*.tex
      
