name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build PDFs
      run: (cd ./docs/HazardAnalysis && latexmk HazardAnalysis.tex)
      
    - name: List files in HazardAnalysis directory
      run: ls -R docs/HazardAnalysis

    - name: List files in docs directory
      run: ls ./docs/*/*.pdf

    - name: Set Git user info
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"

    - name: Mark repository as safe
      run: git config --global --add safe.directory /__w/OKKM.insights/OKKM.insights

    - name: Check Git status
      run: git status

    - name: Add and commit updated PDFs
      run: |
        git add ./docs/*/*.pdf
        git commit -m "Update generated PDFs" || echo "No changes to commit"
        
    - name: Push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push https://x-access-token:${GH_TOKEN}@github.com/OlegGlo/OKKM.insights.git
