name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - 'docs/**'

jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build PDFs
      run: |
        (cd ./docs/HazardAnalysis && latexmk -pdf HazardAnalysis.tex)
        (cd ./docs/DevelopmentPlan && latexmk -pdf DevelopmentPlan.tex)
        (cd ./docs/ProblemStatementAndGoals && latexmk -pdf ProblemStatement.tex)

    - name: List files in docs directory
      run: ls -R docs

    - name: Mark repository as safe
      run: git config --global --add safe.directory /__w/OKKM.insights/OKKM.insights

    - name: Set Git user info
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "PDF BUILDER"

    - name: Check Git status
      run: git status

    - name: List tracked files
      run: git ls-files

    - name: Force add PDFs
      run: |
        git add -f ./docs/*/*.pdf
        git status

    - name: Commit and push updated PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git commit -m "Update generated PDFs" || echo "No changes to commit"
        git push origin main
