name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: build pdfs
      run: latexmk ./docs/HazardAnalysis/HazardAnalysis.tex

      
