name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Build PDFs
      run: (cd ./docs/HazardAnalysis && latexmk HazardAnalysis.tex)
      
    - name: List files in HazardAnalysis directory
      run: ls -R docs/HazardAnalysis

    - name: List files in docs directory
      run: ls ./docs/*/*.pdf

    - name: Mark repository as safe
      run: git config --global --add safe.directory /__w/OKKM.insights/OKKM.insights

    - name: Check Git status
      run: git status

    - name: Add and commit updated PDFs
      run: |
        git add ./docs/*/*.pdf
        git commit -m "Update generated PDFs" || echo "No changes to commit"
        git push
