name: "build_latex"

on:
  push:
    branches: [ main ]
    paths:
    - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'docs/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Mark repository as safe
      run: git config --global --add safe.directory /__w/OKKM.insights/OKKM.insights
      
    - name: build pdfs
      run: (cd ./docs/HazardAnalysis && latexmk HazardAnalysis.tex)
      
    - name: Commit and push updated PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git user
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        git config --global --add safe.directory /__w/OKKM.insights/OKKM.insights
        
        # Add the generated PDFs to the repo
        git add ./docs/*/*.pdf
        
        # Commit changes
        git commit -m "Update generated PDFs"
        
        # Push changes to the main branch
        git push origin main




      
